#=
# `PEPit.jl` tutorial: Gradient descent on smooth (possibly nonconvex) objectives

## Overview

This tutorial reproduces the example in
`examples/nonconvex_optimization/gradient_descent.jl` as a literate Julia script.

We use performance estimation programming (PEP) to compute the smallest constant
$\tau(n, L, \gamma)$ such that Equation @eq-gd-target holds for fixed-step gradient descent
on the class of $L$-smooth functions.

## Problem statement

We consider

$$
f_\star \triangleq \min_x f(x),
$$ {#eq-gd-objective}

where $f$ is $L$-smooth (without assuming convexity).

Our target guarantee is

$$
\min_{0 \le t \le n}\|f'(x_t)\|^2 \le \tau(n,L,\gamma)\,\bigl(f(x_0)-f(x_n)\bigr),
$$ {#eq-gd-target}

with iterates generated by fixed-step gradient descent.

## Algorithm

The iteration is

$$
x_{t+1}=x_t-\gamma f'(x_t), \qquad t=0,1,\dots,n-1,
$$ {#eq-gd-update}

which we encode symbolically in `PEPit.jl` through oracle calls and affine updates.
=#

#=
## Imports

Load the core package and ordered dictionary support used by this repository's examples.
=#

using PEPit # import PEPit types and modeling routines
using OrderedCollections # import OrderedDict for parameter passing
using Clarabel # import Clarabel optimizer backend for conic SDP solving
using PGFPlotsX, LaTeXStrings # import plotting backend and LaTeX-friendly strings for axis labels

#=
## Function: `wc_gradient_descent`

### What this function computes

For given $(L,\gamma,n)$, this routine builds and solves a PEP whose objective is the minimum
recorded gradient norm squared along the trajectory, normalized by
$f(x_0)-f(x_n)\le 1$. The returned `PEPit_tau` is the worst-case value of that metric.

For comparison, we also compute the standard reference value

$$
\tau_{\mathrm{theory}} = \frac{4}{3}\frac{L}{n},
$$ {#eq-gd-theory}

and report both numbers.
=#

function wc_gradient_descent(L, gamma, n; verbose=true) # build and solve the worst-case PEP for fixed-step GD
    problem = PEP() # instantiate an empty performance estimation problem

    param = OrderedDict("L" => L) # store smoothness metadata for the declared function class
    func = declare_function!(problem, SmoothFunction, param; reuse_gradient=true) # declare an $L$-smooth function with reusable gradients

    x0 = set_initial_point!(problem) # create symbolic initial iterate $x_0$
    g0, f0 = oracle!(func, x0) # query $(f'(x_0), f(x_0))$ from the oracle model

    x = x0 # initialize current iterate to $x_0$
    gx, fx = g0, f0 # initialize current oracle pair to iteration $t=0$
    set_performance_metric!(problem, gx^2) # register $\|f'(x_0)\|^2$ as a candidate for the final minimum

    for i in 1:n # execute $n$ fixed-step gradient iterations
        x = x - gamma * gx # apply $x_{t+1}=x_t-\gamma f'(x_t)$
        gx, fx = oracle!(func, x) # evaluate $(f'(x_i), f(x_i))$ at the new iterate
        set_performance_metric!(problem, gx^2) # register $\|f'(x_i)\|^2$ so the model minimizes over all recorded steps
    end # finish the gradient descent loop

    set_initial_condition!(problem, f0 - fx <= 1) # impose normalization $f(x_0)-f(x_n)\le 1$

    PEPit_tau = solve!(problem; solver=Clarabel.Optimizer, verbose=verbose) # solve the SDP with Clarabel and recover the worst-case constant

    theoretical_tau = 4 / 3 * L / n # compute Equation @eq-gd-theory for baseline comparison

    if verbose # print a textual comparison when requested
        println("*** Example file: worst-case performance of gradient descent with fixed step-size ***") # print experiment title
        println("\tPEPit guarantee:\t min_i ||f'(x_i)||^2 <= $(round(PEPit_tau, digits=6)) (f(x_0)-f_*)") # display PEP-computed guarantee
        println("\tTheoretical guarantee:\t min_i ||f'(x_i)||^2 <= $(round(theoretical_tau, digits=6)) (f(x_0)-f_*)") # display theoretical guarantee
    end # close the verbose-printing branch

    return PEPit_tau, theoretical_tau # return both the computed and baseline constants
end # close function definition

#=
## Example run

We now reproduce the same demonstration call as in the original example file.
=#

L = 1.0 # set smoothness constant for the demo instance
gamma = 1.0 # set fixed step-size $\gamma=1/L$ for the demo instance
n = 5 # set the number of iterations in the demo instance
PEPit_val, theoretical_val = wc_gradient_descent(L, gamma, n; verbose=true) # execute the workflow and collect both outputs

#=
## Expected console output (illustrative)

The exact solver logs may differ by machine and solver backend, but the final summary lines
should have the same structure:

````text
*** Example file: worst-case performance of gradient descent with fixed step-size ***
    PEPit guarantee:      min_i ||f'(x_i)||^2 <= 0.266667 (f(x_0)-f_*)
    Theoretical guarantee: min_i ||f'(x_i)||^2 <= 0.266667 (f(x_0)-f_*)
````
=#

#=
## Consistency check

This assertion verifies that the computed baseline matches Equation @eq-gd-theory.
=#

@assert theoretical_val == 4 / 3 * L / n # verify the theoretical baseline formula exactly

#=
## References

[1] A. B. Taylor (2017).
*Convex interpolation and performance estimation of first-order methods for convex optimization*.
PhD Thesis, UCLouvain.

[2] H. Abbaszadehpeivasti, E. de Klerk, M. Zamani (2021).
*The exact worst-case convergence rate of the gradient method with fixed step lengths for L-smooth functions*.
Optimization Letters, 16(6), 1649-1661.
=#

#=
## Sweep over iteration counts and plot the bound

To visualize how the guarantee evolves with the number of iterations $N$, we now sweep
over $N \in \{n_{\min},\dots,n_{\max}\}$ and compute both:

1. the PEPit coefficient $\tau_N$ returned by `wc_gradient_descent`, and
2. the theoretical coefficient $\frac{4L}{3N}$.

For each $N$, these coefficients satisfy

$$
\min_{0\le i\le N}\|f'(x_i)\|^2 \le \tau_N\,\bigl(f(x_0)-f(x_N)\bigr).
$$ {#eq-gd-sweep-coeff}

Because $\frac{4L}{3N}$ scales like $1/N$, we expect the theoretical curve to be strictly
decreasing as $N$ increases.
=#

function run_sweep_and_plot(; L=1.0, gamma=1.0, n_min=1, n_max=20, verbose=false) # sweep over $N$ values and plot PEPit vs theory coefficients
    @assert n_min >= 1 "n_min must be at least 1." # enforce valid lower bound for the iteration sweep
    @assert n_max >= n_min "n_max must be greater than or equal to n_min." # enforce an ordered sweep range

    n_values = collect(n_min:n_max) # build the grid of iteration counts $N$
    pepit_values = Vector{Float64}(undef, length(n_values)) # allocate storage for PEPit coefficients $\tau_N$
    theoretical_values = Vector{Float64}(undef, length(n_values)) # allocate storage for theoretical coefficients $4L/(3N)$

    for (idx, n_current) in pairs(n_values) # iterate through all sweep values with their array positions
        pepit_tau, theoretical_tau = wc_gradient_descent(L, gamma, n_current; verbose=verbose) # compute PEPit and theoretical coefficients at the current $N$
        pepit_values[idx] = pepit_tau # store the PEPit coefficient at index `idx`
        theoretical_values[idx] = theoretical_tau # store the theoretical coefficient at index `idx`
    end # finish computing all sweep values

    @assert length(n_values) == (n_max - n_min + 1) # verify the sweep length equals the requested integer interval size
    @assert length(pepit_values) == length(theoretical_values) == length(n_values) # verify all result arrays are aligned element-wise
    @assert all(diff(theoretical_values) .< 0) "Theoretical values must be strictly decreasing in n." # verify monotonic decay of the theoretical $1/N$ profile
    @assert all(isapprox.(theoretical_values, (4 / 3) * L ./ n_values; rtol=1e-12, atol=0.0)) # verify numerical consistency with $\frac{4L}{3N}$

    pepit_coords = collect(zip(n_values, pepit_values)) # package $(N,\tau_N^{\mathrm{PEPit}})$ points for plotting
    theory_coords = collect(zip(n_values, theoretical_values)) # package $(N,\tau_N^{\mathrm{theory}})$ points for plotting

    @pgf axis = Axis( # build a PGFPlots axis object containing both curves
        { # configure axis-level display options
            width = "13.5cm", # set plot width
            height = "8.3cm", # set plot height
            title = "Gradient Descent on Smooth Nonconvex Functions", # set plot title
            xlabel = L"Number of Iterations $N$", # label the horizontal axis by iteration count
            ylabel = L"Worst-case coefficient $\tau_N$ for $\min_{i\leq N}\|f'(x_i)\|^2$", # label the vertical axis with the correct metric coefficient
            legend_pos = "north east", # place legend in the upper-right corner
            axis_lines = "box", # draw full boxed axes
        }, # end axis configuration
        PlotInc( # add the PEPit curve
            { # configure line appearance for the PEPit curve
                color = "{rgb,255:red,11;green,114;blue,133}", # set PEPit curve color
                mark = "o", # use circular markers for PEPit points
                line_width = "3pt", # set PEPit line thickness
            }, # end PEPit appearance configuration
            Coordinates(pepit_coords), # pass PEPit coordinate data
        ), # end PEPit plot component
        LegendEntry(L"$\texttt{PEPit.jl}$ Bound"), # add legend label for the PEPit curve
        PlotInc( # add the theoretical curve
            { # configure line appearance for the theoretical curve
                color = "{rgb,255:red,230;green,119;blue,0}", # set theoretical curve color
                "no marks", # disable point markers for the theoretical curve
                line_width = "2pt", # set theoretical line thickness
            }, # end theoretical appearance configuration
            Coordinates(theory_coords), # pass theoretical coordinate data
        ), # end theoretical plot component
        LegendEntry(L"\textrm{Theoretical Bound}"), # add legend label for the theoretical curve
    ) # finish constructing the axis object

    picture = TikzPicture(axis) # wrap the axis into a TikZ picture for saving

    output_base = joinpath(@__DIR__, "gradient_descent_pepit_vs_theory_n$(n_min)_n$(n_max)") # define base output path in the tutorial directory
    tex_path = output_base * ".tex" # construct path for TikZ/TeX output
    png_path = output_base * ".png" # construct path for PNG output
    pdf_path = output_base * ".pdf" # construct path for PDF output

    pgfsave(tex_path, picture) # save TeX output unconditionally
    pgfsave(pdf_path, picture) # save PDF output unconditionally
    png_saved = false # initialize flag tracking whether PNG export succeeds
    try # attempt optional PNG export
        pgfsave(png_path, picture) # save PNG output if backend support is available
        png_saved = true # mark PNG export as successful
    catch err # handle PNG export failure without interrupting the tutorial run
        println("Warning: PNG export failed ($(sprint(showerror, err))). Continuing with TEX/PDF outputs.") # report PNG failure while preserving successful TeX/PDF outputs
    end # close PNG export error-handling block

    println("Saved plot (TEX): ", tex_path) # print TeX artifact path
    println("Saved plot (PDF): ", pdf_path) # print PDF artifact path
    if png_saved # branch on PNG export status
        println("Saved plot (PNG): ", png_path) # print PNG artifact path when available
    else # otherwise report PNG omission
        println("PNG plot was not saved.") # inform that PNG was skipped or failed
    end # close PNG status branch
    println("PEPit values: first=", pepit_values[1], ", last=", pepit_values[end]) # summarize endpoint values of the PEPit curve
    println("Theoretical values: first=", theoretical_values[1], ", last=", theoretical_values[end]) # summarize endpoint values of the theoretical curve

    return n_values, pepit_values, theoretical_values, png_path, pdf_path # return sweep data and output paths for downstream use
end # close the sweep-and-plot helper function

#=
## Generate the sweep plot

This default call runs the sweep and writes figure artifacts in the same directory as this
tutorial file.
=#

n_grid, pepit_grid, theory_grid, png_file, pdf_file = run_sweep_and_plot(; L=1.0, gamma=1.0, n_min=1, n_max=20, verbose=false) # run the default sweep and collect outputs
