using PEPit
using OrderedCollections

@doc raw"""
    wc_bregman_proximal_point(gamma, n; verbose=true)

# Problem statement

Compute a PEPit worst-case guarantee for `wc_bregman_proximal_point`.

Consider the composite convex minimization problem

```math
F_\star \triangleq \min_x \{F(x) \equiv f_1(x)+f_2(x) \}
```

where $f_1(x)$ and $f_2(x)$ are closed convex proper functions.

# Performance metric

This code computes a worst-case guarantee for **Bregman Proximal Point** method.
That is, it computes the smallest possible $\tau(n, \gamma)$ such that the guarantee

```math
F(x_n) - F(x_\star) \leqslant \tau(n, \gamma) D_{f_1}(x_\star; x_0)
```

is valid, where $x_n$ is the output of the **Bregman Proximal Point** (BPP) method,
where $x_\star$ is a minimizer of $F$, and when $D_{f_1}$ is the Bregman distance
generated by $f_1$.

# Algorithm
Bregman proximal point is described in [1, Section 2, equation (9)]. For $t \in \{0, \dots, n-1\}$,

```math
    \begin{aligned}
        x_{t+1} & = & \arg\min_{u \in R^n} f_1(u) + \frac{1}{\gamma} D_{f_2}(u; x_t), \\
        D_h(x; y) & = & h(x) - h(y) - \nabla h (y)^T(x - y).
    \end{aligned}
```
# Theoretical guarantee
A **tight** empirical guarantee can be guessed from the numerics

```math
F(x_n) - F(x_\star) \leqslant \frac{1}{\gamma n} D_{f_1}(x_\star, x_0).
```

# References


[[1] Y. Censor, S.A. Zenios (1992).
Proximal minimization algorithm with D-functions.
Journal of Optimization Theory and Applications, 73(3), 451-464.](https://link.springer.com/content/pdf/10.1007/BF00940051.pdf)

# Arguments
- `gamma`: step-size parameter.
- `n`: number of iterations.
- `verbose`: print example and solver progress information when true.

# Returns
- `pepit_tau`: worst-case value.
- `theoretical_tau`: theoretical value.

# Julia usage
```julia
PEPit_tau, theoretical_tau = wc_bregman_proximal_point(3.0, 5; verbose=true)
# Returns approximately: (PEPit_tau, theoretical_tau) = (0.066667, 0.066667)
```
"""
function wc_bregman_proximal_point(gamma, n; verbose=true)
    problem = PEP()


    f1 = declare_function!(problem, ConvexFunction, OrderedDict(); reuse_gradient=false)
    f2 = declare_function!(problem, ConvexFunction, OrderedDict(); reuse_gradient=false)


    xs = stationary_point!(f1)
    fs = value!(f1, xs)
    gf2s, f2s = oracle!(f2, xs)


    x0 = set_initial_point!(problem)
    gf20, f20 = oracle!(f2, x0)


    set_initial_condition!(problem, f2s - f20 - gf20 * (xs - x0) <= 1)


    sx = gf20
    local f1_val::Expression
    for i in 1:n
        x, sx, f2x, g1x, f1_val = bregman_proximal_step!(sx, f2, f1, gamma)
    end


    set_performance_metric!(problem, f1_val - fs)


    PEPit_tau = solve!(problem; verbose=verbose)


    theoretical_tau = 1 / (gamma * n)

    if verbose
        println("*** Example file: worst-case performance of the Bregman Proximal Point in function values ***")
        println("\tPEPit guarantee:\t F(x_n)-F_* <= $(round(PEPit_tau, digits=7)) Dh(x_*; x_0)")
        println("\tTheoretical guarantee:\t F(x_n)-F_* <= $(round(theoretical_tau, digits=7)) Dh(x_*; x_0)")
    end

    return PEPit_tau, theoretical_tau
end


PEPit_tau, theoretical_tau = wc_bregman_proximal_point(3.0, 5; verbose=true)
