using PEPit
using OrderedCollections

@doc raw"""
    wc_improved_interior_algorithm(L, mu, c, lam, n; verbose=true)

# Problem statement

Compute a PEPit worst-case guarantee for `wc_improved_interior_algorithm`.

Consider the composite convex minimization problem

```math
F_\star \triangleq \min_x \{F(x) \equiv f_1(x) + f_2(x)\},
```

where $f_1$ is a $L$-smooth convex function, and $f_2$ is a closed convex indicator function.
We use a kernel function $h$ that is assumed to be closed, proper, and strongly convex (see [1, Section 5]).

# Performance metric

This code computes a worst-case guarantee for **Improved interior gradient algorithm** (IGA).
That is, it computes the smallest possible $\tau(\mu,L,c,\lambda,n)$ such that the guarantee

```math
F(x_n) - F(x_\star) \leqslant \tau(\mu,L,c,\lambda,n)  (c D_h(x_\star;x_0) + f_1(x_0) - f_1(x_\star))
```

is valid, where $x_n$ is the output of the IGA and where $x_\star$ is a minimizer of $F$ and
$D_h$ is the Bregman distance generated by $h$.

In short, for given values of $\mu$, $L$, $c$, $\lambda$ and $n$,
$\tau(\mu,L,c,\lambda,n)$ is computed as the worst-case value of $F(x_n)-F_\star$
when $c  D_h(x_\star;x_0) + f_1(x_0) - f_1(x_\star)\leqslant 1$.

# Algorithm

The IGA is described in [1, "Improved Interior Gradient Algorithm"]. For $t \in \{0, \dots, n-1\}$,

```math
    \begin{aligned}
        \alpha_t & = & \frac{\sqrt{(c_t\lambda)^2+4c_t\lambda}-\lambda c_t}{2},\\
        y_t & = & (1-\alpha_t) x_t + \alpha_t z_t,\\
        c_{t+1} & = & (1-\alpha_t)c_t,\\
        z_{t+1} & = & \arg\min_{z} \left\{ \left< z;\frac{\alpha_t}{c_{t+1}}\nabla f_1(y_t)\right> +f_2(z)+D_h(z;z_t)\right\}, \\
        x_{t+1} & = & (1-\alpha_t) x_t + \alpha_t z_{t+1}.
    \end{aligned}
```
# Theoretical guarantee

The following **upper** bound can be found in [1, Theorem 5.2]:

```math
F(x_n) - F_\star \leqslant \frac{4L}{c n^2}\left(c  D_h(x_\star;x_0) + f_1(x_0) - f_1(x_\star) \right).
```

# References


[[1] A. Auslender, M. Teboulle (2006).
Interior gradient and proximal methods for convex and conic optimization.
SIAM Journal on Optimization 16.3 (2006): 697-725.](https://epubs.siam.org/doi/pdf/10.1137/S1052623403427823)

# Arguments
- `L`: smoothness or Lipschitz parameter, as used by the modeled class.
- `mu`: strong convexity or monotonicity parameter, as used by the modeled class.
- `c`: initial value.
- `lam`: the step-size.
- `n`: number of iterations.
- `verbose`: print example and solver progress information when true.

# Returns
- `pepit_tau`: worst-case value.
- `theoretical_tau`: theoretical value.

# Julia usage
```julia
pepit_tau, theoretical_tau = wc_improved_interior_algorithm(1.0, 1.0, 1.0, 1.0, 5; verbose=true)
# Returns approximately: (pepit_tau, theoretical_tau) = (0.06807, 0.111111)
```
"""
function wc_improved_interior_algorithm(L, mu, c, lam, n; verbose=true)
    problem = PEP()


    func1 = declare_function!(problem, SmoothConvexFunction, OrderedDict("L" => L); reuse_gradient=true)
    func2 = declare_function!(problem, ConvexIndicatorFunction, OrderedDict("D" => Inf); reuse_gradient=false)
    h = declare_function!(problem, StronglyConvexFunction, OrderedDict("mu" => mu); reuse_gradient=true)


    func = func1 + func2


    xs = stationary_point!(func)
    fs = value!(func, xs)
    ghs, hs = oracle!(h, xs)


    x0 = set_initial_point!(problem)
    gh0, h0 = oracle!(h, x0)
    g10, f10 = oracle!(func1, x0)


    x = x0
    z = x0
    g = g10
    gh = gh0
    ck = c
    for k in 0:(n - 1)
        alphak = (sqrt((ck * lam)^2 + 4 * ck * lam) - lam * ck) / 2
        ck = (1 - alphak) * ck
        y = (1 - alphak) * x + alphak * z
        if k >= 1
            g, _ = oracle!(func1, y)
        end
        z, _, _ = bregman_gradient_step!(g, gh, h + func2, alphak / ck)
        x = (1 - alphak) * x + alphak * z
        gh, _ = oracle!(h, z)
    end


    set_initial_condition!(problem, (hs - h0 - gh0 * (xs - x0)) * c + f10 - fs <= 1)


    set_performance_metric!(problem, value!(func, x) - fs)

    pepit_tau = solve!(problem; verbose=verbose)
    theoretical_tau = (4 * L) / (c * (n + 1)^2)

    if verbose
        println("*** Example file: worst-case performance of the Improved interior gradient algorithm in function values ***")
        println("\tPEPit guarantee:\t F(x_n)-F_* <= $(round(pepit_tau, digits=7)) (c * Dh(xs;x0) + f1(x0) - F_*)")
        println("\tTheoretical guarantee:\t F(x_n)-F_* <= $(round(theoretical_tau, digits=7)) (c * Dh(xs;x0) + f1(x0) - F_*)")
    end

    return pepit_tau, theoretical_tau
end


pepit_tau, theoretical_tau = wc_improved_interior_algorithm(1.0, 1.0, 1.0, 1.0, 5; verbose=true)
