using PEPit, OrderedCollections, Clarabel

@doc raw"""
    wc_no_lips_in_function_value(L, gamma, n; solver=Clarabel.Optimizer, verbose=true)

# Problem statement

Compute a PEPit worst-case guarantee for `wc_no_lips_in_function_value`.

Consider the constrainted composite convex minimization problem

```math
F_\star \triangleq \min_x \{F(x) \equiv f_1(x) + f_2(x)\},
```

where $f_1$ is convex and $L$-smooth relatively to $h$,
$h$ being closed proper and convex,
and where $f_2$ is a closed convex indicator function.

# Performance metric

This code computes a worst-case guarantee for the **NoLips** method.
That is, it computes the smallest possible $\tau(n, L)$ such that the guarantee

```math
F(x_n) - F_\star \leqslant \tau(n, L) D_h(x_\star; x_0),
```

is valid, where $x_n$ is the output of the **NoLips** method,
where $x_\star$ is a minimizer of $F$,
and where $D_h$ is the Bregman divergence generated by $h$.
In short, for given values of $n$ and $L$,
$\tau(n, L)$ is computed as the worst-case value of
$F(x_n) - F_\star$ when $D_h(x_\star; x_0) \leqslant 1$.

# Algorithm
This method (also known as Bregman Gradient, or Mirror descent) can be found in,
e.g., [2, Algorithm 1]. For $t \in \{0, \dots, n-1\}$,

```math
x_{t+1} = \arg\min_{u} \{f_2(u)+\langle \nabla f_1(x_t) \mid u - x_t \rangle + \frac{1}{\gamma} D_h(u; x_t)\}.
```

# Theoretical guarantee


The **tight** guarantee obtained in [2, Theorem 1] is

```math
F(x_n) - F_\star \leqslant \frac{1}{\gamma n} D_h(x_\star; x_0),
```

for any $\gamma \leq \frac{1}{L}$; tightness is provided in [2, page 23].

# References
NoLips was proposed [1] for convex problems involving relative smoothness.
The worst-case analysis using a PEP, as well as the tightness are provided in [2].

[[1] H.H. Bauschke, J. Bolte, M. Teboulle (2017).
A Descent Lemma Beyond Lipschitz Gradient Continuity: First-Order Methods Revisited and Applications.
Mathematics of Operations Research, 2017, vol. 42, no 2, p. 330-348.](https://cmps-people.ok.ubc.ca/bauschke/Research/103.pdf)

[[2] R. Dragomir, A. Taylor, A. d'Aspremont, J. Bolte (2021).
Optimal complexity and certification of Bregman first-order methods.
Mathematical Programming, 1-43.](https://arxiv.org/pdf/1911.08510.pdf)

# Arguments
- `L`: smoothness or Lipschitz parameter, as used by the modeled class.
- `gamma`: step-size parameter.
- `n`: number of iterations.
- `solver`: JuMP optimizer constructor used to solve the generated SDP.
- `verbose`: print example and solver progress information when true.

# Returns
- `pepit_tau`: worst-case value.
- `theoretical_tau`: theoretical value.

# Julia usage
```julia
pepit_tau, theoretical_tau = wc_no_lips_in_function_value(L, gamma, 3; verbose=true)
```
"""
function wc_no_lips_in_function_value(L, gamma, n; solver=Clarabel.Optimizer, verbose=true)

    problem = PEP()


    d = declare_function!(problem, ConvexFunction, OrderedDict(); reuse_gradient=true)
    func1 = declare_function!(problem, ConvexFunction, OrderedDict(); reuse_gradient=true)
    h = (d + func1) / L

    func2 = declare_function!(problem, ConvexIndicatorFunction, OrderedDict("D" => Inf); reuse_gradient=false)

    func = func1 + func2


    xs = stationary_point!(func)
    ghs, hs = oracle!(h, xs)
    gfs, fs = oracle!(func1, xs)


    x0 = set_initial_point!(problem)
    gh0, h0 = oracle!(h, x0)
    gf0, f0 = oracle!(func1, x0)


    set_initial_condition!(problem, hs - h0 - gh0 * (xs - x0) <= 1)


    gfx = gf0
    ffx = f0
    ghx = gh0
    for i in 1:n
        x, _, _ = bregman_gradient_step!(gfx, ghx, func2 + h, gamma)
        gfx, ffx = oracle!(func1, x)
        gdx = gradient!(d, x)
        ghx = (gdx + gfx) / L
    end


    set_performance_metric!(problem, ffx - fs)


    pepit_tau = solve!(problem; solver=solver, verbose=verbose)


    theoretical_tau = 1 / (gamma * n)

    if verbose
        println("*** Example file: worst-case performance of the NoLips in function values ***")
        println("\tPEPit guarantee:\t F(x_n) - F_* <= $(round(pepit_tau, digits=6)) Dh(x_*; x_0)")
        println("\tTheoretical guarantee:\t F(x_n) - F_* <= $(round(theoretical_tau, digits=6)) Dh(x_*; x_0)")
    end

    return pepit_tau, theoretical_tau
end


L = 1.0
gamma = 1 / (2 * L)
pepit_tau, theoretical_tau = wc_no_lips_in_function_value(L, gamma, 3; verbose=true)
